name: GradzixCombatSystem
version: '${project.version}'
main: me.xxgradzix.gradzixcombatsystem.GradzixCombatSystem
api-version: '1.21'

commands:
  atrybut:
    description: Pokazuje atrybuty gracza

  atributeItem:
    description: daje itemki
    permission: gradzixcombatsystem.atrybuty

  upgradeItem:
    description: ulepsza itemki
    permission: gradzixcombatsystem.atrybuty

  openUpgradeGui:
    description: otwiera gui do reforgowania itemów
    permission: gradzixcombatsystem.upgrade

  openEnchantGui:
    description: otwiera gui do enchantowania itemów
    permission: gradzixcombatsystem.enchant

  openWitchGui:
    description: otwiera gui wiedzmy
    permission: gradzixcombatsystem.witch