name: GradzixCombatSystem
version: '1.0-SNAPSHOT'
main: me.xxgradzix.gradzixcombatsystem.GradzixCombatSystem
api-version: '1.17'

commands:
  atrybut:
    description: Pokazuje atrybuty gracza
    permission: gradzixcombatsystem.atrybuty