name: GradzixCombatSystem
version: '1.0-SNAPSHOT'
main: me.xxgradzix.gradzixcombatsystem.GradzixCombatSystem
api-version: '1.21'

commands:
  atrybut:
    description: Pokazuje atrybuty gracza

  atributeItem:
    description: daje itemki
    permission: gradzixcombatsystem.atrybuty

  upgradeItem:
    description: ulepsza itemki
    permission: gradzixcombatsystem.atrybuty

  openReforgeGui:
    description: otwiera gui do reforgowania itemów
    permission: gradzixcombatsystem.atrybuty